In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
drug_moa_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-MOA.csv')
drug_contraindication_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-Contraindication.csv')
drug_drug_intraction_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-Drug-Interaction.csv')
drug_indication_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-Indication.csv')
drug_pathway_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-Pathway.csv')
drug_target_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/L1 intermediate DDR results/Drug-Target.csv')
drug_df = pd.read_csv('/content/drive/MyDrive/Thesis_5_1/data/drug-nodes.csv')

In [4]:
def make_DDR1(df):
  neighbour_matrix = np.zeros(214)
  labels = df['cluster-label'].to_numpy()
  repeat_labels = np.repeat(labels.T,214, axis=0).reshape(214,214)
  proximity_matrix = (repeat_labels == repeat_labels.T).astype(int)
  return proximity_matrix

In [5]:
df_moa_matrix = make_DDR1(drug_moa_df)
df_contra_matrix = make_DDR1(drug_contraindication_df)
df_target_matrix = make_DDR1(drug_target_df)
df_path_matrix = make_DDR1(drug_pathway_df)
df_inter_matrix = make_DDR1(drug_drug_intraction_df)
df_ind_matrix = make_DDR1(drug_indication_df)

In [6]:
df_moa_matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [7]:
list_relation = [df_moa_matrix,df_contra_matrix,df_target_matrix,df_path_matrix,df_inter_matrix,df_ind_matrix]

In [11]:
DDR_temp = np.sum(list_relation, axis=0)

In [12]:
DDR_temp

array([[6, 1, 2, ..., 0, 0, 0],
       [1, 6, 3, ..., 0, 0, 1],
       [2, 3, 6, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 6, 1, 0],
       [0, 0, 0, ..., 1, 6, 0],
       [0, 1, 0, ..., 0, 0, 6]])

In [13]:
DDR = DDR_temp/6
DDR

array([[1.        , 0.16666667, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.16666667, 1.        , 0.5       , ..., 0.        , 0.        ,
        0.16666667],
       [0.33333333, 0.5       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.16666667,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.16666667, 1.        ,
        0.        ],
       [0.        , 0.16666667, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [14]:
pd.DataFrame(DDR).to_csv("/content/drive/MyDrive/Thesis_5_1/data/DDR1.csv")